services:
  - type: web
    name: arabic-voice-assistant
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python voice_server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
